### ISSUE TITLE
Intégration en tant que third party

### ISSUE THREAD

**Issue by ericsiber** [ozidna/FizzBuzzKata#1]
La documentation ne précise pas comment intégrer la librairie en tant que 3rd party dans une application Node existante et y lancer la fonction permettant l'affichage de la liste des 100 éléments.

En tentant de le faire, aucun affichage ne se produit.

**Comment by ozidna** [comment]
j'ai oublié de modifier le README quand j'ai ajouté la VERSION 3,
j'ai modifié le README.
j'ai oublié de demander l’installation de node.

**Comment by ericsiber** [comment]
Le README ne précise toujours pas ce qu'il faut faire pour intégrer la librairie dans une application Node existante et l'appeler.

**Comment by ozidna** [comment]
j'ai modifie le README
