### ISSUE TITLE
Fonctionnement de la librairie lorsque le diviseur est le même

### ISSUE THREAD

**Issue by ericsiber** [ozidna/FizzBuzzKata#3]
Cf. cas de test ajouté dans #2

**Comment by ozidna** [comment]
j'ai ajouté le teste demander dans le Pull requests, j'ai modifié le code pour que le test passe

**Comment by ericsiber** [comment]
L'exécution pour les paramètres (2, 2) ne correspond pas au résultat attendu : 

> Merci de saisir le multiple de Fizz,?  
> 
> 2
> 
> Merci de saisir le multiple de Buzz?  
> 
> 2
> FizzBuzz,FizzBuzz,FizzBuzz,FizzBuzz,FizzBuzz,FizzBuzz,FizzBuzz,FizzBuzz,FizzBuzz,FizzBuzz,FizzBuzz,FizzBuzz,FizzBuzz,FizzBuzz,FizzBuzz,FizzBuzz,FizzBuzz,FizzBuzz,FizzBuzz,FizzBuzz,FizzBuzz,FizzBuzz,FizzBuzz,FizzBuzz,FizzBuzz,FizzBuzz,FizzBuzz,FizzBuzz,FizzBuzz,FizzBuzz,FizzBuzz,FizzBuzz,FizzBuzz,FizzBuzz,FizzBuzz,FizzBuzz,FizzBuzz,FizzBuzz,FizzBuzz,FizzBuzz,FizzBuzz,FizzBuzz,FizzBuzz,FizzBuzz,FizzBuzz,FizzBuzz,FizzBuzz,FizzBuzz,FizzBuzz,FizzBuzz,FizzBuzz,FizzBuzz,FizzBuzz,FizzBuzz,FizzBuzz,FizzBuzz,FizzBuzz,FizzBuzz,FizzBuzz,FizzBuzz,FizzBuzz,FizzBuzz,FizzBuzz,FizzBuzz,FizzBuzz,FizzBuzz,FizzBuzz,FizzBuzz,FizzBuzz,FizzBuzz,FizzBuzz,FizzBuzz,FizzBuzz,FizzBuzz,FizzBuzz,FizzBuzz,FizzBuzz,FizzBuzz,FizzBuzz,FizzBuzz,FizzBuzz,FizzBuzz,FizzBuzz,FizzBuzz,FizzBuzz,FizzBuzz,FizzBuzz,FizzBuzz,FizzBuzz,FizzBuzz,FizzBuzz,FizzBuzz,FizzBuzz,FizzBuzz,FizzBuzz,FizzBuzz,FizzBuzz,FizzBuzz,FizzBuzz,FizzBuzz

**Comment by ozidna** [comment]
j'ai pas compris au début, en fait j'ai trouvé le beug qui permet de affiché ce résultat,
j'ai corrigé la version3 (sur le master ) et aussi la viersion 2
Merci
